# Generated by Django 2.2.17 on 2021-03-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='concert_img'),
        ),
    ]
