# Generated by Django 2.2.17 on 2021-04-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
